= Docker
:toc:

== Introduction 

Docker quick start, in order to give key idea, quick start

From 

 * https://docs.docker.com/engine/getstarted
 * https://hub.docker.com/
 * https://blogs.technet.microsoft.com/virtualization/2016/10/18/use-docker-compose-and-service-discovery-on-windows-to-scale-out-your-multi-service-container-application/
 * Package manager : https://docs.google.com/presentation/d/1JuNunEmZk8zQf2lJccUP1YfJYRPWzHxgkhD9GQaQIFw/edit#slide=id.g1bba50e503_0_55  



== Starting to use docker 

docker run docker/whalesay cowsay Laurent
....
  _________
< Laurent >
 ---------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/

....

Now we can create a docker image. 
vi Dockerfile

[source]
----

FROM docker/whalesay:latest
RUN apt-get -y update && apt-get install -y fortunes
CMD /usr/games/fortune -a | cowsay
----
		  
docker build -t docker-whale .
 
....
 Sending build context to Docker daemon 2.048 kB
Step 1/3 : FROM docker/whalesay:latest
 ---> 6b362a9f73eb
Step 2/3 : RUN apt-get -y update && apt-get install -y fortunes
 ---> Running in 0257993e408a
Ign http://archive.ubuntu.com trusty InRelease
Get:1 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
.....
Setting up fortunes (1:1.99.1-7) ...
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
 ---> 68db4fb43d30
Removing intermediate container 0257993e408a
Step 3/3 : CMD /usr/games/fortune -a | cowsay
 ---> Running in 2d736170de01
 ---> 2e261c9e4cbb
Removing intermediate container 2d736170de01
Successfully built 2e261c9e4cbb
....


NOTE: to check local images now, run : docker images
 
....
 REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
docker-whale        latest              2e261c9e4cbb        35 minutes ago      256 MB
docker/whalesay     latest              6b362a9f73eb        21 months ago       247 MB
....
 
docker run docker-whale

....
  _______________________________________
/ On Monday mornings I am dedicated to  \
| the proposition that all men are      |
| created jerks.                        |
|                                       |
| -- H. Allen Smith, "Let the Crabgrass |
\ Grow"                                 /
 ---------------------------------------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/

....

Now, let's tag the image and push it to docker hub

....
docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
docker-whale        latest              2e261c9e4cbb        About an hour ago   256 MB
docker/whalesay     latest              6b362a9f73eb        21 months ago       247 MB

docker tag 2e261c9e4cbb ouelcum/docker-whale:1.0

docker images
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
docker-whale           latest              2e261c9e4cbb        About an hour ago   256 MB
ouelcum/docker-whale   1.0                 2e261c9e4cbb        About an hour ago   256 MB
docker/whalesay        latest              6b362a9f73eb        21 months ago       247 MB
....
 
Now, we are ready to push it 
....

docker login

Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: ouelcum
Password:
Login Succeeded

docker push ouelcum/docker-whale

The push refers to a repository [docker.io/ouelcum/docker-whale]
9287995a542b: Pushing 1.083 MB/9.431 MB
5f70bf18a086: Pushed
d061ee1340ec: Pushed
d511ed9e12e1: Pushed
091abc5148e4: Pushed
b26122d57afa: Pushing 1.056 MB/58.56 MB
37ee47034d9b: Pushed
528c8710fd95: Pushed
1154ba695078: Pushing 525.3 kB/188.1 MB

....

We can delete local images
docker  image remove 2e261c9e4cbb (it will remove both images, we can also run docker image remove docker-whale:latest)

If we run again the image locally, it try to fetch it, most of the stuff is present locally, just run it
....
docker run ouelcum/docker-whale:1.0
Unable to find image 'ouelcum/docker-whale:1.0' locally
1.0: Pulling from ouelcum/docker-whale
4fe767775744: Already exists
c464cf84c0e1: Already exists
af18d94c8f7b: Already exists
a3ed95caeb02: Already exists
21e782d076bd: Already exists
ac3159f8a827: Already exists
ed1f77a892d5: Already exists
cb3cb5695f26: Already exists
16ac0bcde243: Already exists
Digest: sha256:85c05b72310498980af71c89cc5c8603a0380d00f39cfdf27669fb5cb72b9042
Status: Downloaded newer image for ouelcum/docker-whale:1.0
 ______________________________________
/ Everything should be built top-down, \
\ except the first time.               /
 --------------------------------------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/
....