= Azure 
:toc:

== Introduction 



== Installation

.Step 1: Install PowerShellGet

Installing items from the PowerShell Gallery requires the PowerShellGet module. Make sure you have the appropriate version of PowerShellGet and other system requirements. Run the following command to see if you have PowerShellGet installed on your system.

 Get-Module PowerShellGet -list | Select-Object Name,Version,Path

You should see something similar to the following output:

 Name          Version Path
 ----          ------- ----
 PowerShellGet 1.0.0.1 C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PowerShellGet.psd1

If you do not have PowerShellGet installed, see the How to get PowerShellGet section of this article.

.Step 2: Install Azure PowerShell

Installing Azure PowerShell from the PowerShell Gallery requires elevated privileges. Run the following command from an elevated PowerShell session:

 # Install the Azure Resource Manager modules from the PowerShell Gallery
 Install-Module AzureRM

[Note]
 If you have a version older than 2.8.5.201 of NuGet, you will be prompted to download and install the latest version of NuGet.
 
 
The AzureRM module is a rollup module for the Azure Resource Manager cmdlets. When you install the AzureRM module, any Azure Resource Manager module that has not previously been installed will be downloaded and installed from the PowerShell Gallery.

Once the module is installed, you need to load the module into your PowerShell session. Modules are loaded using the Import-Module cmdlet, as follows:

 Import-Module AzureRM
