name: Build on commit
on:
  push:
    branches:
      - '*' # ou la branche de votre choix
    paths:
      - '**/*.java' # ou le chemin exact si vous ne voulez déclencher que sur certains fichiers
      - '**/*.md' #files md and asciidoc may breack this documentation module
      - '**/*.adoc' #need to add also images
      - '**/*.xml'
      - 'pom.xml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn package
